# Generated by Django 5.1.1 on 2024-10-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0002_alter_photo_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tag_category',
            field=models.CharField(choices=[('nature', 'nature'), ('art', 'art'), ('scenery', 'scenery'), ('landscape', 'landscape')], default='nature', max_length=40),
        ),
    ]
